version: "3.8"
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
        - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379

  flagsbackend:
    image: flagsbackend
    container_name: flagsbackend
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080