version: "3.8"
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-flags_db}
      POSTGRES_USER: ${POSTGRES_USER:-flags_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
        - 5432:5432
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis-data:/bitnami/redis/data
    expose:
      - 6379
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  flagsbackend:
    image: flagsbackend
    container_name: flagsbackend
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - 8080:8080